language: java

jdk:
- openjdk10

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
install: true

matrix:
  include:
  - jdk: openjdk10
    before_install:
    - rm "${JAVA_HOME}/lib/security/cacerts"
    - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle

addons:
  sonarcloud:
    organization: "stefanorocks"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner